### ISSUE TITLE
Automate and/or deprecate this repository

### ISSUE THREAD

**Issue by technicalpickles** [hubot-scripts/hubot-example#9]
Hubot has had a [script generator](https://github.com/github/generator-hubot) for awhile now, so this repository isn't as necessary anymore. I could still see it being useful to poke around an example without having to setup your environment, but then again asking potential users to use the generator seems reasonable. Another option might be doing something with `generator-hubot` releases to update this repository afterwards.

cc @hubot-scripts/owners @bkeepers @michaelansel @bhuga

**Comment by technicalpickles** [comment]
Done in https://github.com/hubot-scripts/hubot-example/issues/10

**Comment by patcon** [comment]
Oh hey, I'm not seeing an obvious reference for how to generate scripts with that linked generator (neither readme nor scripting.md doc).

https://github.com/github/hubot/blob/master/docs/scripting.md
https://github.com/github/generator-hubot

Am I simply missing a link?

**Comment by technicalpickles** [comment]
@patcon I noticed that so filed too so filed https://github.com/github/hubot/issues/968 . I also added (briefly) instructions to the README.
